apiVersion: ENC[AES256_GCM,data:4XU=,iv:+IzPdwiO51gGY8HqeZWQv2CQZe3ohWWEnGNHGhrvEhs=,tag:tnKdxh0TCxH7/u8KgaX/Bw==,type:str]
kind: ENC[AES256_GCM,data:UScpDL4/,iv:iC7DH6UWATiiK/XLFi2J5FLwvxZfrhmo90ZOGN3GL5o=,tag:wrE9vvNNrnSekWKtMi9yWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qqIM5k3YTGf4VPE=,iv:CV3ZOcvTFEO3hZnlIMkxTnlflJvEFGsHOoju14bbLWc=,tag:ZAy0PaE+PnkXwB/TEXDT5A==,type:str]
    namespace: ENC[AES256_GCM,data:YoHIvVBx,iv:cxseaAOVsLRAz3uPcZi6DRYE7cpxt0IVbA+FXgBt5lo=,tag:6IwxLeKiefT3LBf+vISDVg==,type:str]
type: ENC[AES256_GCM,data:9iqEricb,iv:jkazHtDWayrfbCW8pI8Z9HiF8S5L+LJFepcGsLafgKI=,tag:J6SNjodioPRdz3J1oRfBQw==,type:str]
stringData:
    SQLD_AUTH_JWT_KEY: ENC[AES256_GCM,data:IsmbS0pMWT+6HdJj8fPBGYLSerPGVx0HIYWaq9ggFwWzngbo+Nz0e8F7fA==,iv:d5w+C9Rt1yIBlpuGfFIQr+xG1GNCJB1WAuF9yW9Oqso=,tag:0j3dC5F2NrDmbd3V1gSkXQ==,type:str]
    SQLD_AUTH_JWT_PRIVATE_KEY_PEM: ENC[AES256_GCM,data:fUt1KCkJO2bnu5U7aX2bA1anpzxA1aNAcX/qOlWHtsxb6bKeBrdr4LIkK7wFp6oJOBDfBbmL1hekWiZLyPot0dMNllmuJ9DPiBy6upT57vsPD6rrYkCZBM387OxGUtANMZo02tvJ4n1fgyeCTbzCuq2Hh7wYHw==,iv:AyqpOjWYmJug4/oQ2dIt/TNbUzHftJCnYpShxlLPq/8=,tag:RKu2Ng/6EUzJzQz/r6DMJw==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEY0VGS0Nvd1g5c2kvdWVt
            S0x2UER0NmxXOWw4d3Z2WG1KTFRnYWV2LzBFCnVHZHc1NG0xSUdpREJGNi9FYmU1
            YkdZMGtkN2xZS1pReEZTQXBUM2dqbU0KLS0tIHc2bTVlM1BSZjFVbzJuT1BVT0w0
            ZUJFUElTOWFZWXhqR01pQldpTS9VaW8KEtu0xw1Wc55F8MNqj4M5rFQzzpV7phhs
            eNI9FUMaD7J5ug9S8G5ENgIDVF/QLw4gols85KI6p++WXJ1Xx/wepg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T01:51:34Z"
    mac: ENC[AES256_GCM,data:ROFABTVk4J4P8VP9ws+7R25ao7ktOLWGELX+ZW3qun0+gi9JpQSKiU9RfeDeqAtUHVGj+F+Oj7NYZ53doC7T7pe2YwIUl/EP8IWzz/8hkF4k3ceOvaXpLkPtkeeBykva7QWfoQi+J5cMzt/mWciN6WrrxoJ23Vm75KYKr0Hgt0k=,iv:PqnFM/UDFD2oPeF811E+3wCS3isIsIpMoHRjYpWH2JU=,tag:SanONOu7YT7uFfnq8OfbhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:tL8=,iv:N7KLT0zv2wBXBFt43O24dfyRpcoJadp/TgCJbhNkUIU=,tag:09Yq0uEchR8bfaNkglVZ9Q==,type:str]
kind: ENC[AES256_GCM,data:GRaeQQe8,iv:ywCp77fUr/T8GyZ3/fpV61T2hGh/3TcGmK85pXR2gN0=,tag:FOnTblRwYJ4JAeu+u1gE6A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uaGrbDkazq4S/w==,iv:Ry7O5R3t8V34mgOll7gqcdomtwH7YZgp4etIF/VI3BE=,tag:PZvi+kSHzpt8sd8uzYyiGQ==,type:str]
    namespace: ENC[AES256_GCM,data:WMaB6Hk0,iv:QpZY5rNvCXjoqORbf7sRZyFm928ylLej9JeIZEn77dM=,tag:EM8jZN5iOZ5xH8TDYzqvAA==,type:str]
type: ENC[AES256_GCM,data:KPeaieDL,iv:1hiiupCecOWAsMFKlo8oPOX3u5MH62IZwhmMO60fMqs=,tag:szNp2Ti+uSggyhtZ4CPrhQ==,type:str]
stringData:
    KOPIA_REPOSITORY_PASSWORD: ENC[AES256_GCM,data:4UbjljQD8xa5oPFgfAiknU6aWFecIlJfaMhH1NimaXsHIXyuBb64s8gXNPrywIrA5wtbOH7pRiqIm2inigCXOQ==,iv:UUehWuO7KCj8UkNbPnGfEJv8pf7oCoCNnKEBviv0yRY=,tag:x07nCL09JuIWrPi1hktElg==,type:str]
    KOPIA_SERVER_HOSTNAME: ENC[AES256_GCM,data:9XUt9f+dB3PUtmHGikXUKZI=,iv:LnSpR6sOcaD4ISkBL71j8wcOdt77+d9m+buXtNDDAEs=,tag:MwIm5g2hQOmWfGc7i+TTpg==,type:str]
    KOPIA_SERVER_USERNAME: ENC[AES256_GCM,data:0pUoFQYfAaYkAl+2g3BmHkub897wc1t1M8UM874Jtuu6s7ve6czOBv/a4BlzgWwWHKbtmJcY0LrYnDCosCvtuw==,iv:0RldR6ZuUxjSaj+QjUgQ7lRjjuxgFVZhwyzWvYwqe8M=,tag:TNTNcPDw9dHHN8AO4rJT+A==,type:str]
    KOPIA_SERVER_PASSWORD: ENC[AES256_GCM,data:4biPe/y+LgzhmRm2kBsiaaWgrTTsE8HG8xP5GBNILdjfgbi5HhthBH6l4f3RZC5zQWxuNBK6S8ML5WogyZCoTw==,iv:qlDTdeCxMeOpPzP7yMqWk18YMW4MN8vjUezz/O607pM=,tag:qijwbH4ZQc0guax/ordCLw==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEY0VGS0Nvd1g5c2kvdWVt
            S0x2UER0NmxXOWw4d3Z2WG1KTFRnYWV2LzBFCnVHZHc1NG0xSUdpREJGNi9FYmU1
            YkdZMGtkN2xZS1pReEZTQXBUM2dqbU0KLS0tIHc2bTVlM1BSZjFVbzJuT1BVT0w0
            ZUJFUElTOWFZWXhqR01pQldpTS9VaW8KEtu0xw1Wc55F8MNqj4M5rFQzzpV7phhs
            eNI9FUMaD7J5ug9S8G5ENgIDVF/QLw4gols85KI6p++WXJ1Xx/wepg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T01:51:34Z"
    mac: ENC[AES256_GCM,data:ROFABTVk4J4P8VP9ws+7R25ao7ktOLWGELX+ZW3qun0+gi9JpQSKiU9RfeDeqAtUHVGj+F+Oj7NYZ53doC7T7pe2YwIUl/EP8IWzz/8hkF4k3ceOvaXpLkPtkeeBykva7QWfoQi+J5cMzt/mWciN6WrrxoJ23Vm75KYKr0Hgt0k=,iv:PqnFM/UDFD2oPeF811E+3wCS3isIsIpMoHRjYpWH2JU=,tag:SanONOu7YT7uFfnq8OfbhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:ZHQ=,iv:JgDdKkElPjP+g1vJ42rxLNlhKu6zi7ny9tKGxqqDOAQ=,tag:i03V0lg/uHdunTqg9alMDA==,type:str]
kind: ENC[AES256_GCM,data:o2fGLpqH,iv:vXbjCb1LiSIVSql8i6FGi9xEr8bELLWDQtpH/qnGYAU=,tag:e71AVxAQLTUljqYnKKYoww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2AT1jc7PypfPE134SUn81g==,iv:lBbaJlnVivRQ30cPPxO51Z3fncX1ZAS3dY4LRldWZgs=,tag:uS8euFlAf7+j4LJL8bAY9w==,type:str]
    namespace: ENC[AES256_GCM,data:V/LzyVHr,iv:IgTi+Gzu4i0oDOQtJpyOWb47Q0ByrIAp8e2fJQxViaM=,tag:oQ+PZCm78VyvH0vR3kmgZw==,type:str]
type: ENC[AES256_GCM,data:+9MA1oOA,iv:Qb6YdGD26bdFkZ1Ava5a524bYAb/GMFWKpteCZPWw/4=,tag:eqlERNijXA1MAT5155IEPw==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:1DzSfnDGB0Jdx6Tu8uFXZU+JgAfxpyk5T1YVc0fxbmrMUgVXNDp5T8s0i111ks1VJfUEXh7EWNeow2DCzm4LxA==,iv:c3QVRPj/2J99T/zdD64ZqZaBCbriDhB5LMsN3cBbeAE=,tag:g0iCJTZUZxS3sf8RboVSYQ==,type:str]
    password: ENC[AES256_GCM,data:n4oZvOqcKxZdb25wjreR8HLnAPPf+oxMu+7uibt960oW31f+AwpMcZsZbhtmOQ10Saj0h6l15283gx3t9fq+bg==,iv:faWR+hCjhC93uicy3CtgCNRCo1eWscge6+Mv2RtmjvE=,tag:uIURz2hBV3lTFY2a8Py3Sg==,type:str]
    replication-password: ENC[AES256_GCM,data:D/ybr3Mjy+RNhivkcYb+CdCYpXYSE7woAbbZNMMIwmCjhb5LkBBUEbbqBp8EBWK6GixblOOY+zOWNW22+aSuSQ==,iv:bo8naJ62xNy+V0Q5qzkvhq9h2ObQw3PYY8PydRbvx8E=,tag:P6jD7fATK+aiLI+/MEX7EQ==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEY0VGS0Nvd1g5c2kvdWVt
            S0x2UER0NmxXOWw4d3Z2WG1KTFRnYWV2LzBFCnVHZHc1NG0xSUdpREJGNi9FYmU1
            YkdZMGtkN2xZS1pReEZTQXBUM2dqbU0KLS0tIHc2bTVlM1BSZjFVbzJuT1BVT0w0
            ZUJFUElTOWFZWXhqR01pQldpTS9VaW8KEtu0xw1Wc55F8MNqj4M5rFQzzpV7phhs
            eNI9FUMaD7J5ug9S8G5ENgIDVF/QLw4gols85KI6p++WXJ1Xx/wepg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T01:51:34Z"
    mac: ENC[AES256_GCM,data:ROFABTVk4J4P8VP9ws+7R25ao7ktOLWGELX+ZW3qun0+gi9JpQSKiU9RfeDeqAtUHVGj+F+Oj7NYZ53doC7T7pe2YwIUl/EP8IWzz/8hkF4k3ceOvaXpLkPtkeeBykva7QWfoQi+J5cMzt/mWciN6WrrxoJ23Vm75KYKr0Hgt0k=,iv:PqnFM/UDFD2oPeF811E+3wCS3isIsIpMoHRjYpWH2JU=,tag:SanONOu7YT7uFfnq8OfbhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:ReQ=,iv:fPunAGSh3iXa6Tq5QIG4tuH/sXdyku6tY0RI/sYltnc=,tag:A4vY+jVRCE9Ko+KG5NEiaA==,type:str]
kind: ENC[AES256_GCM,data:S/zh3mpG,iv:0oPZL/qNpdkephebxoVN73ypfqnPU/Lw7VfClIdcnF4=,tag:Z9X2+I7mwQftbadeS23ivg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xuhs6sN07hmzFQKwtFN//28pSw==,iv:91dYK+xOGmCqjaBc7Dpb61HVDIzKAwszUZi6LEkPgmg=,tag:Z/AyshTy3+J6ziF40j00iQ==,type:str]
    namespace: ENC[AES256_GCM,data:yaG/9gSY,iv:lJoA2lUOhHDWOOpp1yoLTPWiiLA98kX/wBKBiwEG4/Y=,tag:+Lxs7yNP5wlJ+uLHTSu+5w==,type:str]
type: ENC[AES256_GCM,data:BHK26h06,iv:+rv5pZakP1EhmlW3xKfp3JJU80+12FvmPzV7kqkzB7c=,tag:I/D1Z7dh6e9Deuay07itIA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:R+9wOMzpkrp2IzTgZI9ZSI4zbMdVzIMbbFQyCOhX+mBAKA2WHjDNxBJAl+APuU+PAoHxL10uc9qbM5YL6iYMBQ==,iv:U5yBCRnDOerc9i0W5qwPS8S4kL59musYtt8jj1P8PJU=,tag:ipuKTV659eSHK+InYY/iMA==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEY0VGS0Nvd1g5c2kvdWVt
            S0x2UER0NmxXOWw4d3Z2WG1KTFRnYWV2LzBFCnVHZHc1NG0xSUdpREJGNi9FYmU1
            YkdZMGtkN2xZS1pReEZTQXBUM2dqbU0KLS0tIHc2bTVlM1BSZjFVbzJuT1BVT0w0
            ZUJFUElTOWFZWXhqR01pQldpTS9VaW8KEtu0xw1Wc55F8MNqj4M5rFQzzpV7phhs
            eNI9FUMaD7J5ug9S8G5ENgIDVF/QLw4gols85KI6p++WXJ1Xx/wepg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T01:51:34Z"
    mac: ENC[AES256_GCM,data:ROFABTVk4J4P8VP9ws+7R25ao7ktOLWGELX+ZW3qun0+gi9JpQSKiU9RfeDeqAtUHVGj+F+Oj7NYZ53doC7T7pe2YwIUl/EP8IWzz/8hkF4k3ceOvaXpLkPtkeeBykva7QWfoQi+J5cMzt/mWciN6WrrxoJ23Vm75KYKr0Hgt0k=,iv:PqnFM/UDFD2oPeF811E+3wCS3isIsIpMoHRjYpWH2JU=,tag:SanONOu7YT7uFfnq8OfbhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:yeI=,iv:j1HMeLg6pMIKgDKoS1FnKMJQnSpzbfeTLb4EjlPAXNI=,tag:ezOM4x7yfxna5kdltycNgQ==,type:str]
kind: ENC[AES256_GCM,data:/ShBjZY5,iv:/vUpnFmO++hmiR+CeVJMZLsnuMLwhjJnZK1qFhD4LVI=,tag:jbA1pSMI4Da40OuUc8PicQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FYhA12AokMK//JPU2mdO8QSelA==,iv:bPFl+q7AGEZlXgJLUVWwDA5nE3P10VC0dc2swOOqYKo=,tag:1i0IyvAZeXTuC1bCGa4g/A==,type:str]
    namespace: ENC[AES256_GCM,data:TKk4GE7i,iv:cfUMCJsc25IgeZZFjwBaRIZNJD1ZJA/yyFfEcINatqI=,tag:t/Y2QhGwQuAPmyCkVb3mTQ==,type:str]
type: ENC[AES256_GCM,data:0gZjGBqn,iv:ebEI5mX930KblHvCkHccvlNBNnrrdUXdGrOWwGJRDyg=,tag:SYd7Hyn+2GlfL28ZtlTT7g==,type:str]
stringData:
    API_KEY: ENC[AES256_GCM,data:5vmyU6BoGuaCDw7Oxe6NizFrEQWJII1A6fwu26pF74vekWbPc6mOd6jYGw==,iv:jCKL1wDdIBE8UYAnVCNO/Ew/GT3RT4bpEETF+IdGzj0=,tag:24tyHEzsl6iQnpSkbemphQ==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEY0VGS0Nvd1g5c2kvdWVt
            S0x2UER0NmxXOWw4d3Z2WG1KTFRnYWV2LzBFCnVHZHc1NG0xSUdpREJGNi9FYmU1
            YkdZMGtkN2xZS1pReEZTQXBUM2dqbU0KLS0tIHc2bTVlM1BSZjFVbzJuT1BVT0w0
            ZUJFUElTOWFZWXhqR01pQldpTS9VaW8KEtu0xw1Wc55F8MNqj4M5rFQzzpV7phhs
            eNI9FUMaD7J5ug9S8G5ENgIDVF/QLw4gols85KI6p++WXJ1Xx/wepg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T01:51:34Z"
    mac: ENC[AES256_GCM,data:ROFABTVk4J4P8VP9ws+7R25ao7ktOLWGELX+ZW3qun0+gi9JpQSKiU9RfeDeqAtUHVGj+F+Oj7NYZ53doC7T7pe2YwIUl/EP8IWzz/8hkF4k3ceOvaXpLkPtkeeBykva7QWfoQi+J5cMzt/mWciN6WrrxoJ23Vm75KYKr0Hgt0k=,iv:PqnFM/UDFD2oPeF811E+3wCS3isIsIpMoHRjYpWH2JU=,tag:SanONOu7YT7uFfnq8OfbhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:zAo=,iv:IHeSH0gWv+6ATQ574Mi7Mnu5xBJpWJLiE4C2FObbJ/s=,tag:L9mRy7C+WniGtra6N5m3Qg==,type:str]
kind: ENC[AES256_GCM,data:LksjK9lT,iv:sopJcmPxn3akPDwjGYO8oaJGC88vvsbk7EQpcJW2fSg=,tag:k31O6UjqafYDiBZt3eSzrg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nmXja+yMP3gsTvpHnyMYSrAp,iv:4mR5NPOR3PHxqpxrs1FTVteXGb41IY1+/jZC2N1xc0A=,tag:ThXYR6H4j4H8MlokbI7lag==,type:str]
    namespace: ENC[AES256_GCM,data:XK90ViiA2DPrB70=,iv:nJ/WsRu50Aren5sC7V6pRppn6La4BV6WBYYtGIkqPLo=,tag:SdwnZtXwm4kSh36MJZjtag==,type:str]
type: ENC[AES256_GCM,data:QczvO/jU,iv:VpsaFPkJyede9oDtcg14FNyXdsBtSSzN15sOHoYGgXI=,tag:blooFKJp5C5hM1kqfdPWEg==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:mjos98UjDXp1SatcWPZn0G6UynycO5MHv2LUZ2Gt89Yn/+CszTTOYCD5oC73BI21+0EHoTZEYEJBznqyaZs/fA==,iv:efeTSmjcLi9sdCRHrjcHBocUZrD9S9U0NFQ1/Xn4VCE=,tag:dje4uISn9Vhr2HWN0nUoIg==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEY0VGS0Nvd1g5c2kvdWVt
            S0x2UER0NmxXOWw4d3Z2WG1KTFRnYWV2LzBFCnVHZHc1NG0xSUdpREJGNi9FYmU1
            YkdZMGtkN2xZS1pReEZTQXBUM2dqbU0KLS0tIHc2bTVlM1BSZjFVbzJuT1BVT0w0
            ZUJFUElTOWFZWXhqR01pQldpTS9VaW8KEtu0xw1Wc55F8MNqj4M5rFQzzpV7phhs
            eNI9FUMaD7J5ug9S8G5ENgIDVF/QLw4gols85KI6p++WXJ1Xx/wepg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T01:51:34Z"
    mac: ENC[AES256_GCM,data:ROFABTVk4J4P8VP9ws+7R25ao7ktOLWGELX+ZW3qun0+gi9JpQSKiU9RfeDeqAtUHVGj+F+Oj7NYZ53doC7T7pe2YwIUl/EP8IWzz/8hkF4k3ceOvaXpLkPtkeeBykva7QWfoQi+J5cMzt/mWciN6WrrxoJ23Vm75KYKr0Hgt0k=,iv:PqnFM/UDFD2oPeF811E+3wCS3isIsIpMoHRjYpWH2JU=,tag:SanONOu7YT7uFfnq8OfbhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:Uss=,iv:Ft4veo8+WOnOdJROBfGoz5dL6Z2tRHxKP8PcAhdiv4Y=,tag:nJEQzvbOOOgqqm7LnQt1LQ==,type:str]
kind: ENC[AES256_GCM,data:eYZwid1p,iv:eHjX0ZlJUDtUrUrBLg84T2fzASOn1akWBSVUplgFqtg=,tag:8cPKYkqMizgEDk6LGrXygQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RBy3KShcChnJg82BNRc=,iv:KBRbI0iufSU4DVPhwqtTToPQx+e5w6ee5iMzv7tqwU8=,tag:zEFW75mkPNxiXnhWw6P1xw==,type:str]
    namespace: ENC[AES256_GCM,data:OZSlnS44rA==,iv:kGWbImF+zWrfm2Ry0EHrkW3a4i09kRsKWOy/khrfCrc=,tag:DcUPeluES6Ob+2hP8Bwe4A==,type:str]
type: ENC[AES256_GCM,data:BdwhTjz2,iv:95hNa84Gn9NvRZUFW7LHbETVtnIb/OCm7OK/pHLai2o=,tag:wcgz9zDoLUxEvYISGWZFkA==,type:str]
stringData:
    TUWUNEL_REGISTRATION_TOKEN: ENC[AES256_GCM,data:Jr6sXPRoHZxSJnK9rlx5wPgH/XyB51lSnMLMcORgWShSp10rrsnNS8VyG/B4i6bSqsXmIQbSEMclNRw6n0O8Nw==,iv:wfGFEiLXbGCHkqS4SwXM2Hu1BNw13rUQOeDLPlrS5IE=,tag:2HHCPcu3bSZExAZZvAE30w==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEY0VGS0Nvd1g5c2kvdWVt
            S0x2UER0NmxXOWw4d3Z2WG1KTFRnYWV2LzBFCnVHZHc1NG0xSUdpREJGNi9FYmU1
            YkdZMGtkN2xZS1pReEZTQXBUM2dqbU0KLS0tIHc2bTVlM1BSZjFVbzJuT1BVT0w0
            ZUJFUElTOWFZWXhqR01pQldpTS9VaW8KEtu0xw1Wc55F8MNqj4M5rFQzzpV7phhs
            eNI9FUMaD7J5ug9S8G5ENgIDVF/QLw4gols85KI6p++WXJ1Xx/wepg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T01:51:34Z"
    mac: ENC[AES256_GCM,data:ROFABTVk4J4P8VP9ws+7R25ao7ktOLWGELX+ZW3qun0+gi9JpQSKiU9RfeDeqAtUHVGj+F+Oj7NYZ53doC7T7pe2YwIUl/EP8IWzz/8hkF4k3ceOvaXpLkPtkeeBykva7QWfoQi+J5cMzt/mWciN6WrrxoJ23Vm75KYKr0Hgt0k=,iv:PqnFM/UDFD2oPeF811E+3wCS3isIsIpMoHRjYpWH2JU=,tag:SanONOu7YT7uFfnq8OfbhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
