apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-stack
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-stack
  template:
    metadata:
      labels:
        app: immich-stack
    spec:
      containers:
        - name: immich-stack
          image: ghcr.io/majorfi/immich-stack:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: immich-stack-secret
                  key: API_KEY
            - name: API_URL
              value: http://immich-server:2283/api
            - name: RUN_MODE
              value: cron
            - name: CRON_INTERVAL
              value: "3600"
            - name: TZ
              value: Australia/Sydney
